---
title: 'Types of Digital Narratives'
teaching: 10
exercises: 2
---


## Types of digital narratives 

-	Traditional Linear Stories (Non-Interactive)
-	Traditional Linear Stories (Interactive)
-	Non-Linear Stories (Interactive) 
  -	Multiple-Ending Stories
  -	Branching path Stories
  -	Open-ended stories
  -	Player Driven Stories (Open Worlds)
  -	more...
 
Fig. 8 - Narrative as Virtual Reality 2: Revisiting Immersion and Interactivity in Literature by Ryan, Marie-Laure. Via annemarleen.gitbook.io https://annemarleen.gitbook.io/immersive-design/class-0-2/class-1


### Traditional Linear Stories (Non-Interactive)
E-Books, Films, Documentaries, Oral stories (Audio Podcast etc...)


The user is not able to make the choice on how to proceed.

Must follow all the events in line with the given narrative.

 
Fig. 10 - eBooks can now be read on a large variety of devices by Per Palmkvist Knudsen, Wekemedia Creative Commons Attribution-Share Alike 3.0

 
Fig. 11 - Poster for the 1960 film The Time Machine by Reynold Brown, Public domain, via Wikimedia Commons


 
Fig. 12 - Graph representig audio files

### Traditional Non-Linear Stories (Non-Interactive)
E-Books, Films, Documentaries





The user is not able to choose how to proceed.

Must follow all the events in the narrative but with the presence of flash-backs and/or flash-forwards.

Sometimes these experiences need to be repeated to understand the plot.
 
Fig. 14 - Diseñadores publicitarios, Public domain, via Wikimedia Commons
Linear Stories (Interactive)



The user is not able to choose the direction of the narrative but can interact with the contents. Can skip contents within the narrative.
 
Fig. 16 – Electronic book with library for free students access vector. Ebook with opened page, man touching screen of tablet. Education printed materials in Cover. By robu_s day under Education License from Adobe Stock


## Non-Linear Stories (Interactive)


The user can make the choice on how to proceed.

 
Fig. 18 - Futuristic virtual reality VR headset technology watching movie playing video interactive augmented simulation hand control user interface Asian man sofa enjoyment at home entertainment living room By Have a nice day under Education License from Adobe Stock


>"Black Mirror Bandersnatch is a very interesting concept. It gives you choices that start out simple like choosing a cereal box for breakfast and steadily moves towards darker decisions. You find yourself choosing who lives and dies and what to destroy and what to save. If we take a look at todays society, most people have become desensitized to so many different things. You are either numb to the world or sheltered from it. And this is the real point I think Bandersnatch is getting at. I found myself choosing bad decisions because I wanted to see how it would turn out. And I'm sure many other people did the same". *Comment by Nicolas A. on Twitter*



## More examples of Non-Linear narratives (Interactive)

### Multiple-ending stories
Usually, they have a well-defined beginning but can branch in different directions with the choice of different ending.


Fig. 20 –- Self-produced graph of the type of narrative –  Multiple ending stories graph.

> "Some games in the Final Fantasy series have multiple or secret endings, the ending depending on the player's actions taken during the game. These can be as simple as minor adjustments to the final story scenes to reflect variable outcomes earlier in the game, or as drastic as entirely different conclusions to the story"
[https://finalfantasy.fandom.com/wiki/Multiple_endings](https://finalfantasy.fandom.com/wiki/Multiple_endings)

 
Fig. 21 - SVG uploaded by Hautala; derivative PNG created by David Levy, Public domain, via Wikimedia Commons

 
### Branch stories

These types of stories branch in different directions but usually the have one ending, the user can make decision along the narrative.

The entire Dragon Age series offers you multiple occasions where they have to make a decision; these choices can be small and change next to nothing, or they can be large plot points that go on to echo in the rest of the sequels.

[https://www.thegamer.com/games-witch-branching-stories/#dragon-age-inquisition](https://www.thegamer.com/games-witch-branching-stories/#dragon-age-inquisition) 

 
### Open ended stories




Fig. 24 -  Self-produced graph of the type of narrative – Open end stories
Can be all the above combined without a specific or well-defined ending. Sometime used in films for sequels.

 
Fig. 25 Assassin’s Creed Gary Ullah from UK, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons


### Player driven stories (Open worlds)
> "People sometimes think "open-world" means an absence of narrative, just complete freedom of choice. But that’s not necessarily the case. In fact, it rarely is."








Fig. 26 – Self produced Player driven stories graph (Open world)


Examples:

- Avalon RPG Game
- Online Since 1984
 
Fig. 27 – Avalon Logo https://en.wikipedia.org/wiki/Avalon:_The_Legend_Lives 

## Storytelling in Heritage Interpretation

>"...interpreters are charged with transforming a seemingly unmanageable amount of information into something suitable for the public."
[https://ncph.org/history-at-work/reinterpreting-freeman-tilden/](https://ncph.org/history-at-work/reinterpreting-freeman-tilden/)

The 6 Freeman Tilden principles from the book «Interpreting Our Heritage».

1. Any interpretation that does not somehow relate what is being displayed or described to something within the personality or experience of the visitor will be sterile. (who’s the audience?)
2. Information, as such, is not Interpretation. Interpretation is revelation based upon information. But they are entirely different things. However all interpretation includes information. (where’s the science?)
3. Interpretation is an art, which combines many arts, whether the materials presented are scientific, historical or architectural. Any art is in some degree teachable.
4. The chief aim of Interpretation is not instruction, but provocation. (what’s the story?)
5. Interpretation should aim to present a whole rather than a part, and must address itself to the whole man rather than any phase. (what’s the story?)
6. Interpretation addressed to children (say up to the age of twelve) should not be a dilution of the presentation to adults, but should follow a fundamentally different approach. To be at its best it will require a separate program. (who’s the audience?)
https://thesciencepresenter.wordpress.com/2011/01/24/6-principles-of-heritage-interpretation/ 

 
Fig. 28 – Freeman Tilden.  English:  Wilber "Bud" E. Dutton, Public domain, via Wikimedia Commons


## Digital Storytelling in Heritage Interpretation.

7 Tips on Digital Storytellinggiven by Europeana

1. Be Personal
2. Be informal but expert
3. Tell hidden stories
4. Illustrate your points
5. Signpost your journey
6. Be specific
7. Be evocative



### Examples of storytelling in Heritage Interpretation

**Interactive audio**

The reading glove Story embedded on real, physical objects that can be played with and moved around.
[https://www.youtube.com/watch?v=UE6vllYI5RI&t=1s](https://www.youtube.com/watch?v=UE6vllYI5RI&t=1s)
 
Fig. 35 – The Reading Glove https://www.flickr.com/photos/jtanenbaum/sets/72157626471260917/with/5662869791/
http://radar.oreilly.com/2012/03/reading-glove-sensors-reading-experience.html?utm_source=dlvr.it&utm_medium=tumblr&utm_campaign=Feed%3A%20oreilly%2Fradar%2Fatom%20%28O%27Reilly%20Radar%29 
 
 
**Interactive Video**

Italia Terremota: This interactive documentary combines 3D visualisation and multi-modal storytelling to tell the story of Senerchia terremotata, that is, the earthquake that devastated the Irpinia region (South Italy) in 1980.
 
Fig. 36 - Terramota  Image Curtesy of © StoryLab 2017 https://storylabresearch.com/projects/italia-terremotata/ 

**Multi-engagement project**

Emotive: EU-funded research project that works from the premise that cultural sites are highly emotional places.
[https://emotiveproject.eu/pages/summary/index.html](https://emotiveproject.eu/pages/summary/index.html) 
 
Fig. 37 - Screenshot from Emotive project booklet. https://emotiveproject.eu/wp-content/uploads/2019/10/EMOTIVE-booklet-2019-web.pdf  

**Online multidimensional exploration tool**

Tapestry-Cyark: Platform for building and telling place-based stories on web and mobile devices".
[https://tapestry.cyark.org/](https://tapestry.cyark.org/) 

 
Fig. 38 – Screenshot Tapesrty Cyark  https://tapestry.cyark.org/ 


## Tools for digital storytelling in Heritage Interpretation

Narralive Storymaker: https://www.narralive.org/story-maker/ 
Terrastories: https://terrastories.app/
Voyager Story Standalone: https://3d.si.edu/voyager-story-standalone 
Recogito: https://recogito.pelagios.org/
Digital Mappa: https://www.digitalmappa.org/
Allmaps: https://allmaps.org/
Annona: https://ncsu-libraries.github.io/annona/
Adno: https://adno.app/en/ 
Exhibit: https://www.exhibit.so/
Micrio: https://doc.micr.io/iiif/
MLOL: https://iiif.medialibrary.it/stories/
Omeka: https://omeka.org/s/modules/IiifServer/
Spotlight: http://projectblacklight.org/ 
Storiiies Editor: https://storiiies-editor.cogapp.com/ 
Strollview: https://seige.digital/en/strollview/
Wax: https://minicomp.github.io/wax/
Full List at: https://iiif.io/get-started/tools/

### Text and images and video
Twine: https://twinery.org/ 
Inklewriter: https://www.inklestudios.com/inklewriter/
Aesop Storyengine: https://aesopstoryengine.com/ 
Arcgis Storymaps: https://storymaps.arcgis.com/ 
Odyssey: https://cartodb.github.io/odyssey.js/ 
Open-Hypervideo: http://www.open-hypervideo.org/ 
Games and 3D
Unreal Engine: https://www.unrealengine.com/ 
Unity: https://unity.com/
Twinmotion: https://www.twinmotion.com
Visionare Studio: https://www.visionaire-studio.net/ 



 
Fig. 1 – Self-produced graph of the research domains of storytelling

Fig. 2 - US Embassy from New Zealand, Public domain, via Wikimedia Commons This image was originally posted to Flickr by US Embassy New Zealand. https://commons.wikimedia.org/wiki/File:Storytelling_(29663292122).jpg

Fig. 3 - Cute girl reading book Teddy bear. by Volkovslava under Educational License from Adobe Stock

Fig. 4 - Elderly people sitting outdoors around a campfire - senior citizens on a picnic warming themselves by the fire on an autumn night. by Carlo under Education License from Adobe Stock

Fig. 5 Self-produced graphic from worldcloud - https://www.wordclouds.co.uk/

Fig. 6 - Animator creates sketches for the cartoon. Works on the storyboard. Comics Compilation. Storyboard movie layout for pre-production. Creative artwork. Home based set up. By Framestock under Standard License from Adobe Stock

Fig. 7 – Basic steps of digital storytelling graph by Samantha Morra
Fig. 8 - Narrative as Virtual Reality 2: Revisiting Immersion and Interactivity in Literature by Ryan, Marie-Laure. Via annemarleen.gitbook.io https://annemarleen.gitbook.io/immersive-design/class-0-2/class-1

Fig. 9 - Self-produced graph of the type of narrative Non-Linear Stories (Non-Interactive)

Fig. 10 - eBooks can now be read on a large variety of devices by Per Palmkvist Knudsen, Wekemedia Creative Commons Attribution-Share Alike 3.0

Fig. 11 - Poster for the 1960 film The Time Machine by Reynold Brown, Public domain, via Wikimedia Commons

Fig. 12 - Graph representig audio files

Fig. 13 - Self-produced graph of the type of narrative - Non-Linear Stories (Non-Interactive)

Fig. 14 - Memento Film Poster

Fig. 15 - Self-produced graph of the type of narrative - Linear Stories (Interactive)

Fig. 16 – Electronic book with library for free students access vector. Ebook with opened page, man touching screen of tablet. Education printed materials in Cover. By robu_s day under Education License from Adobe Stock

Fig. 17 - Self-produced graph of the type of narrative – Non-Linear Stories (Interactive)

Fig. 18 - Futuristic virtual reality VR headset technology watching movie playing video interactive augmented simulation hand control user interface Asian man sofa enjoinment at home entertainment living room By Have a nice day under Education License from Adobe Stock

Fig. 19 - Black Mirror Logo. By Mark Simonson (font)Vectorisation: User:EEIM (first version); Céréales Killer (second version), Public domain, via Wikimedia Commons

Fig. 20 – Self-produced graph of the type of narrative –  Multiple ending stories graph
Fig. 21 - SVG uploaded by Hautala; derivative PNG created by David Levy, Public domain, via Wikimedia Commons

Fig. 22 - Self-produced graph of the type of narrative – Branch stories

Fig. 23 - greyloch from Washington, DC, area, U.S.A., CC BY-SA 2.0 <https://creativecommons.org/licenses/by-sa/2.0>, via Wikimedia Commons 

Fig. 24 -  Self-produced graph of the type of narrative – Open end stories

Fig. 25 – Assassin’s Creed Gary Ullah from UK, CC BY 2.0 <https://creativecommons.org/licenses/by/2.0>, via Wikimedia Commons 

Fig. 26 - Self produced Player driven stories graph (Open world)

Fig. 27 – Avalon Logo https://en.wikipedia.org/wiki/Avalon:_The_Legend_Lives

Fig. 28 – Freeman Tilden.  English:  Wilber "Bud" E. Dutton, Public domain, via Wikimedia Commons

Fig. 29 - Self produced graph on the base of Tilden principles from https://thesciencepresenter.wordpress.com/2011/01/24/6-principles-of-heritage-interpretation/

Fig. 30 - Seven tips for digital storytelling with cultural heritage by Maggy Szynkielewska, 202, Europeana Foundation, Netherlands, CC BY-SA https://pro.europeana.eu/page/seven-tips-for-digital-storytelling

Fig. 31 -  Farella, Elisa Mariarosaria, Emre Özdemir, and Fabio Remondino. ‘4D Building Reconstruction with Machine Learning and Historical Maps’. Applied Sciences 11, no. 4 (January 2021): 1445. https://doi.org/10.3390/app11041445.

Fig. 32 -  AMM_0004 Museu cidade de ammaia - https://sketchfab.com/3d-models/amm-0004-767641ab76e74c07b4c8fb5b512d48c3

Fig. 33 - Manuscripts Image Puzzles http://blalbrit.github.io/2016-06-06-slide_puzzle.html

Fig. 34 - The Sennedjem Lintel from the Phoebe A. Hearst Museum of Anthropology at the University of California, Berkeley. RTI representation showing color information (bottom portion) and "specular enhancement" mode showing surface shape and enhanced reflectance (top portion). https://culturalheritageimaging.org/Technologies/RTI/

Fig. 35 – The Reading Glove https://www.flickr.com/photos/jtanenbaum/sets/72157626471260917/with/5662869791/

Fig. 36 -  Terramota  Image Curtesy of © StoryLab 2017 https://storylabresearch.com/projects/italia-terremotata/

Fig. 37 - Screenshot from Emotive project booklet. https://emotiveproject.eu/wp-content/uploads/2019/10/EMOTIVE-booklet-2019-web.pdf

Fig. 38 – Screenshot Tapesrty Cyark  https://tapestry.cyark.org/

Fig. 39 Logos for storytelling tools: Narralive https://www.narralive.org/, Smithsonian https://3d.si.edu/labs, Terrastories https://terrastories.app/

Fig. 40 Logos Storytelling tools

Fig. 41 - Schematics and logo IIIFF Framework  https://iiif.io/get-started/how-iiif-works/

Fig. 42 - Logos of Storytelling platforms for heritage interpretation

